### ISSUE TITLE
oscap crashes during audit on the system with ceph-mds package installed

### ISSUE THREAD

**Issue by phausman** [canonical/ubuntu-security-guide#38]
Ubuntu 22.04.4 LTS
usg version: 22.04.6

On the system with ceph-mds package installed, running `usg audit ...` produces report with several rules having "unknown" result. Looking at the logfile produced by `usg audit`, I can see that oscap fails as follows:

```
I: oscap:   Evaluating systemdunitdependency test 'oval:ssg-test_multi_user_wants_rsyslog:tst:1': systemd test.
I: oscap:     Querying systemdunitdependency object 'oval:ssg-object_multi_user_target_for_rsyslog_enabled:obj:1', flags: 0.
I: oscap:     Creating new syschar for systemdunitdependency_object 'oval:ssg-object_multi_user_target_for_rsyslog_enabled:obj:1'.
I: oscap:     Starting probe on URI 'pipe:///usr/lib/x86_64-linux-gnu/openscap/probe_systemdunitdependency'.
I: oscap:     FAIL: recv failed: dsc=0x5640da79d670, errno=4, Interrupted system call.
I: oscap:     FAIL: ctx=0x5640db712780, sd=9, errno=4, Interrupted system call.
W: oscap:     Can't receive message: 4, Interrupted system call.
E: oscap:     Can't close sd: 10, No child processes.
E: oscap:     Recv: retry limit (0) reached.
I: oscap:   Test 'oval:ssg-test_multi_user_wants_rsyslog:tst:1' evaluated as (null).
```

At the same time, crash file is created in /var/crash/_usr_lib_x86_64-linux-gnu_openscap_probe_systemdunitdependency.0.crash.

Rules resulting in "unknown" state:
- Enable systemd-journald Service (xccdf_org.ssgproject.content_rule_service_systemd-journald_enabled)
- Enable rsyslog Service (xccdf_org.ssgproject.content_rule_service_rsyslog_enabled)
- Verify nftables Service is Enabled (xccdf_org.ssgproject.content_rule_service_nftables_enabled)
- Enable cron Service (xccdf_org.ssgproject.content_rule_service_cron_enabled)

Potentially related to:
- https://github.com/OpenSCAP/openscap/issues/1738
- https://github.com/OpenSCAP/openscap/pull/1533

Steps to reproduce:

1. Bootstrap localhost Juju controller 
```
juju bootstrap localhost
```

2. Create two LXD machines for testing
```
# Create reference ubuntu LXD machine
juju deploy ubuntu --series jammy

# Create ceph-mon LXD machine
juju deploy ceph-mon --series jammy --channel quincy/stable
```

3. Push CIS tailoring file to both `ubuntu` and `ceph-mon` machines
```
lxc file push cis_level1_server_tailoring.xml <ubuntu-lxc-machine-name>/home/ubuntu/
lxc file push cis_level1_server_tailoring.xml <ceph-mon-lxc-machine-name>/home/ubuntu/
```

4. Apply CIS hardening on both `ubuntu` and `ceph-mon` machines.

```
# Attach UPro to a machine under test
sudo pro attach <ubuntu-pro-token>

# Enable CIS
sudo pro enable usg

# Install USG
sudo apt-get update --yes && sudo apt-get install --yes usg

# Apply CIS hardening
sudo usg fix --debug --tailoring-file cis_level1_server_tailoring.xml

# Reboot machine after applying the hardening
sudo reboot

# Audit
sudo usg audit --debug --tailoring-file cis_level1_server_tailoring.xml

# Review audit results, check files in /var/lib/usg:
# - remediation-<date>.log
# - usg-report-<date>.html
# - usg-log-<date>.log

# Finally detach Ubuntu Pro if you're not using it anymore
sudo pro detach
```

As a result of this reproducer, the audit on `ceph-mon` machine ends up with rules mentioned above in "unknown" state, while for `ubuntu` machine, audit is successful.

I have compared packages installed on `ubuntu` and `ceph-mon` machines and, by elimination, I identified that ceph-mds package is causing the problem.

Analysing the CoreDump from the .crash file shows that the problem occurs when ceph-mds.target is being analysed. See frame 14 below:

```
#0  0x00007fd7e07e31a8 in _dbus_validate_signature_with_reason () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#1  0x00007fd7e07e39bd in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#2  0x00007fd7e07e3770 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#3  0x00007fd7e07e3a59 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#4  0x00007fd7e07e3c30 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#5  0x00007fd7e07e3da4 in _dbus_validate_body_with_reason () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#6  0x00007fd7e07faf05 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#7  0x00007fd7e07e7157 in _dbus_message_loader_queue_messages () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#8  0x00007fd7e07ef820 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#9  0x00007fd7e07ef95d in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#10 0x00007fd7e07f17b1 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#11 0x00007fd7e07f1c9d in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#12 0x00007fd7e07d65ed in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#13 0x00007fd7e07eadcc in dbus_pending_call_block () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#14 0x00005628b3497d08 in get_property_by_unit_path (conn=conn@entry=0x7fd7cc001d00, unit_path=unit_path@entry=0x7fd7cd03a840 "/org/freedesktop/systemd1/unit/ceph_2dmds_2etarget", 
    property=<optimized out>, property@entry=0x5628b349d3c8 "Requires") at ../../../../src/OVAL/probes/unix/linux/systemdunitdependency.c:82
#15 0x00005628b349823a in get_all_dependencies_by_unit (conn=conn@entry=0x7fd7cc001d00, unit=<optimized out>, cbarg=cbarg@entry=0x7fd7cc0031c0, include_requires=include_requires@entry=true, 
    include_wants=include_wants@entry=true, callback=0x5628b34932f0 <dependency_callback>) at ../../../../src/OVAL/probes/unix/linux/systemdunitdependency.c:149
#16 0x00005628b34981a5 in get_all_dependencies_by_unit (conn=conn@entry=0x7fd7cc001d00, unit=<optimized out>, cbarg=cbarg@entry=0x7fd7cc0031c0, include_requires=include_requires@entry=true, 
    include_wants=include_wants@entry=true, callback=0x5628b34932f0 <dependency_callback>) at ../../../../src/OVAL/probes/unix/linux/systemdunitdependency.c:182
...
```

I have attached tailoring file (xml), audit report (html), audit log and crash file. All in a zip file. [files.zip](https://github.com/canonical/ubuntu-security-guide/files/14886532/files.zip)

**Comment by dodys** [comment]
Issues to usg should be reported in launchpad
